### ISSUE TITLE
Using the plugin with AngularJS ng-repeat

### ISSUE THREAD

**Issue by mlchang** [PebbleRoad/glossarizer#10]
Struggling to hook up the plug in to run over an AngularJS ng-repeat list. I have a function being called successfully after the ng-repeat is ran. However, it is not stepping into .glossarizer and executing the plugin. 
Has anyone ran into similar issues? I understand if this is considered irrelevant to the repo itself as this is more of a jquery = angularjs concern.

**Comment by rmdort** [comment]
Please share a jsfiddle so that i can investigate this issue.
