### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by gomako** [PebbleRoad/glossarizer#12]
I'm trying to make it so that only capitalised occurrences of a word are picked up .i.e:

````term: "Will, !will"````

But this ignores all occurrences of will, regardless of case. I have tried removing "i" from ````var regex = new RegExp('^' + this.clean(term) + '$', 'i');```` to make it case sensitive but it still isn't picking up.

Any ideas on what I can do to get it working for this use case?

Thanks

**Comment by rmdort** [comment]
I have added a new option `caseSensitive` . Please update your version.

So, you can use it like

````
$('.content').glossarizer({
	sourceURL: 'glossary.json',
	caseSensitive: true,
	callback: function(){
		new tooltip();
	}
});
````
