### ISSUE TITLE
Terms not being replaced at all

### ISSUE THREAD

**Issue by johnwbaxter** [PebbleRoad/glossarizer#17]
Hi,

I'm trying to use glossarizer without the tooltip plugin specified. I'm assuming it simply takes the term it finds and wraps it in a abbr tag as standard?

It is running, my json is valid, the terms exist, but it's not wrapping the term in the html and i cannot fathom why.

My code is below, can you see any glaring omissions here or have i misunderstood how this works?

```
<div id="content">
<p>this might be my copy and i would want to find the term clinic in here</p>
</div>
```

```
[
    {
        "term": "clinic,test",
        "description": "test desc"
    }
]

```
```
 $('#content').glossarizer({
            sourceURL: '/glossary/glossary.json',
            lookupTagName : 'p, ul',
            callback: function(){
                alert('glossarizer done');
            }
        });
```

So when all that runs, i'm expecting to see this in the markup?:
`
<p>this might be my copy and i would want to find the term <abbr title="test desc">clinic</abbr> in here</p>`

I load the page and i get the alert that tells me the method has run, but i don't see any changed markup.

Thanks!

**Comment by blfeigel** [comment]
@johnwbaxter, I've been using this for a while, and I'm unable to recreate your issue. I've recreated the example you provided in as [jsfiddle](https://jsfiddle.net/blfeigel/7eqyhpdh/).

**Comment by johnwbaxter** [comment]
@blfeigel Thanks for that! The issue seemed to lie with the selector i was using. Perhaps it was just too broad, but i made the selector much more specific and now it's working great. Thanks again!!
