### ISSUE TITLE
npm release

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [PebbleRoad/glossarizer#26]
Hello,
I am writing on behalf of CERN Open Data team. We really like your library and would like to use it in our project. I was wondering if you consider releasing it on NPM ? If there is no time me and my team can take care preparing the package so as to release it. 
Thank you very much in advance!
Best,
Giannis

**Comment by rmdort** [comment]
Sure. Published - https://www.npmjs.com/package/glossarizer

**Comment by ioannistsanaktsidis** [comment]
Amazing, thank you very much for your quick response. Closing this issue.
