### ISSUE TITLE
tooltip: missing from npm release

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [PebbleRoad/glossarizer#27]
Looks like tooltip folder is missing from the npm release. Is it by accident or do I have to use an external tooltip library ?

**Comment by rmdort** [comment]
Yes its an optional package.

You can either use the tooltip files from the `tooltip` folder or use your own

**Comment by ioannistsanaktsidis** [comment]
Also is it possible to add jquery as dependency and not as  peerDependency https://github.com/PebbleRoad/glossarizer/blob/master/package.json#L26 ? This way we can assure that there will not be any conflicts with required versions of jquery. I am sorry for the inconvenience in advance :)

**Comment by rmdort** [comment]
Done. Pushed.

**Comment by ioannistsanaktsidis** [comment]
Perfect closing issue!
