### ISSUE TITLE
First mention only

### ISSUE THREAD

**Issue by sheldrake** [PebbleRoad/glossarizer#30]
Hi, we're just applying Glossarizer to a new website on the topic of Tech We Trust. Thanks for this. It should really aid those less familiar with the inevitable jargon.

Saying that, can we limit the glossary entry hyperlink to just the first mention on any one page? For example, we have a Glossarizer entry for "Trust", but this means the webpage dedicated to the topic and which therefore mentions the word quite a few times has a lot of repeated Glossarizer links!

Cheers.

**Comment by rmdort** [comment]
You can set `replaceOnce` to `true`

**Comment by sheldrake** [comment]
Damn, that looks too easy. Like it was in the documentation. [_goes to check_] ... ah yes, [here](https://github.com/PebbleRoad/glossarizer/#options). Apologies for not looking. And thanks again.

**Comment by jschroed91** [comment]
@sheldrake @rmdort Should this be closed now?
