### ISSUE TITLE
getDescription Regex is too lenient

### ISSUE THREAD

**Issue by thedamon** [PebbleRoad/glossarizer#6]
if I have in my JSON
    {"term": "black cat", "description":"a black feline"},
    {"term": "cat", "description": "meow"}

Anywhere I use the word "cat" I get the description "a black feline", unless I place the  "cat" definition above "black cat" in my JSON file. Since we're splitting terms by commas, shouldn't getDescription behave the same way?

**Comment by rmdort** [comment]
I cant replicate this issue. Have you tried it with the latest version? 

If not, can you create a fiddle

**Comment by thedamon** [comment]
Hmm I'll have to double check this but thanks for looking into it!

I tried to throw together a jsfiddle but it was not happening with the github links and a json file in a gist. Is there a service you've had luck with for that?
