### ISSUE TITLE
Multiple terms are not working

### ISSUE THREAD

**Issue by kaleemullah** [PebbleRoad/glossarizer#9]
`{`
    `"term": "genetic, !genetic testing, genes, DNA",`
    `"description": "relating to genes or heredity: genetic abnormalities."`
  `}`

For 'genes' and 'DNA', it is returning 'Undefined' in tooltip instead of proper description.

any help?

**Comment by rmdort** [comment]
Issued a fix for this

**Comment by kaleemullah** [comment]
Thanks :+1:
